/* AconSystems • Prompt Maschine • suno_terms.js • v0.1.9 */
import { NONE } from './data.js';

export const SUNO_TERMS_BY_MENU = {
  "1.1": {
    "AFROBEAT": "afrobeat",
    "AMBIENT / DOWNTEMPO": "ambient downtempo",
    "BLUES": "blues",
    "CINEMATIC SCORE": "cinematic score",
    "CLASSICAL / ORCHESTRAL": "classical orchestral",
    "COUNTRY": "country",
    "ELECTRONIC / DANCE": "electronic dance",
    "EXPERIMENTAL / AVANT GARDE": "experimental avant garde",
    "FOLK & ACOUSTIC": "folk acoustic",
    "FUNK": "funk",
    "HIPHOP & RAP": "hiphop rap",
    "INDUSTRIAL": "industrial",
    "JAZZ": "jazz",
    "LATIN": "latin",
    "METAL": "metal",
    "POP": "pop",
    "PUNK": "punk",
    "R&B": "r&b",
    "REGGAE": "reggae",
    "ROCK": "rock",
    "SCHLAGER": "german schlager",
    "SOUL": "soul",
    "SYNTHWAVE / RETROWAVE": "synthwave retrowave",
    "VOLKSMUSIK": "austrian folk volksmusik",
    "WORLD ETHNIC": "world ethnic",
  },
  "1.2": {
    "80s Pop": "80s pop",
    "90s Boom Bap": "90s boom bap",
    "Afro House": "afro house",
    "Afro Pop": "afro pop",
    "Afrobeat (classic)": "afrobeat classic",
    "Afrobeats (modern)": "afrobeats modern",
    "Alpenländische Volksmusik": "alpine folk austrian folk",
    "Alt Rock": "alt rock",
    "Alternative Rock": "alternative rock",
    "Amapiano": "amapiano",
    "Ambient": "ambient",
    "Ambient Drone": "ambient drone",
    "Americana": "americana",
    "Appalachian": "appalachian",
    "Arabian": "arabian",
    "Art Pop": "art pop",
    "Baroque Pop": "baroque pop",
    "Bebop": "bebop",
    "Bedroom Pop": "bedroom pop",
    "Bhangra": "bhangra",
    "Black Metal": "black metal",
    "Blackgaze": "blackgaze",
    "Blasmusik": "brass band oompah",
    "Bluegrass": "bluegrass",
    "Blues": "blues",
    "Blues Rock": "blues rock",
    "Bollywood": "bollywood",
    "Boom Bap": "boom bap",
    "Bossa Nova": "bossa nova",
    "Breakbeat": "breakbeat",
    "Calypso": "calypso",
    "Celtic Folk": "celtic folk",
    "Chalga": "chalga",
    "Chamber Classical": "chamber classical",
    "Chamber Pop": "chamber pop",
    "Chiptune": "chiptune",
    "Cinematic Ambient": "cinematic ambient",
    "Cinematic Score": "cinematic score",
    "City Pop (Japanese 80s)": "city pop japanese 80s",
    "Classic Rock": "classic rock",
    "Classical": "classical",
    "Country": "country",
    "Cumbia Psychodelica": "cumbia psychodelica",
    "Cyberpunk": "cyberpunk",
    "Cyberpunk Industrial": "cyberpunk industrial",
    "Dance Pop": "dance pop",
    "Dancehall": "dancehall",
    "Dark Academia Classical": "dark academia classical",
    "Darkwave": "darkwave",
    "Death Metal": "death metal",
    "Deathcore": "deathcore",
    "Deep House": "deep house",
    "Deutscher Schlager": "german schlager",
    "Disco": "disco",
    "Disco Funk": "disco funk",
    "Djent / Prog Metal": "djent prog metal",
    "Downtempo": "downtempo",
    "Dream Pop": "dream pop",
    "Drift Phonk": "drift phonk",
    "Drill": "drill",
    "Drohne": "drone ambient",
    "Drum & Bass": "drum bass",
    "Dub": "dub",
    "Dubstep": "dubstep",
    "Dungeon Synth": "dungeon synth",
    "Egerländer": "egerlander brass polka",
    "Egyptian": "egyptian",
    "Electro": "electro",
    "Electro Swing": "electro swing",
    "Emo / Midwest Emo": "emo midwest emo",
    "Epic Trailer Music": "epic trailer music",
    "Euphoric Trance": "euphoric trance",
    "Eurodance": "eurodance",
    "Experimental / Avant Garde": "experimental avant garde",
    "Folk": "folk",
    "Folk Metal": "folk metal",
    "Forró": "forró",
    "Freak Folk": "freak folk",
    "Frutiger Aero": "frutiger aero",
    "Funk": "funk",
    "Funk Metal": "funk metal",
    "Future Bass": "future bass",
    "Future Funk": "future funk",
    "Future R&B": "future r&b",
    "G Funk": "g funk",
    "Glam Rock": "glam rock",
    "Glitch Hop": "glitch hop",
    "Gospel": "gospel",
    "Gregorian Chant": "gregorian chant",
    "Grunge": "grunge",
    "Hard Rock": "hard rock",
    "Hardcore Punk": "hardcore punk",
    "Hardstyle": "hardstyle",
    "Heavy Metal": "heavy metal",
    "Heavy Metal Trap": "heavy metal trap",
    "Heurigenmusik": "austrian tavern music folk",
    "High NRG": "high nrg",
    "Highlife": "highlife",
    "Hindustani": "hindustani",
    "HipHop": "hiphop",
    "Horrorcore": "horrorcore",
    "House": "house",
    "Hyperpop / Glitchcore": "hyperpop glitchcore",
    "Hypnagogic": "hypnagogic",
    "Indie Folk": "indie folk",
    "Indie Pop": "indie pop",
    "Indie Rock": "indie rock",
    "Industrial": "industrial",
    "Industrial Metal": "industrial metal",
    "Industrial Rock": "industrial rock",
    "Industrial Techno": "industrial techno",
    "Italian Rock": "italian rock",
    "Italo Disco": "italo disco",
    "Jamaica Groove": "jamaica groove",
    "Japan Pop": "japan pop",
    "Japan Rock": "japan rock",
    "Jazz": "jazz",
    "Jazz Fusion": "jazz fusion",
    "Jewish Music": "jewish music",
    "K Pop": "k pop",
    "Kawaii Metal": "kawaii metal",
    "Klezmer": "klezmer",
    "Latin": "latin",
    "Latin Jazz": "latin jazz",
    "Liquid Drum & Bass": "liquid drum bass",
    "Lo Fi Hip Hop": "lo fi hip hop",
    "Mambo": "mambo",
    "Marschmusik": "marching band",
    "Math Rock": "math rock",
    "Medieval Rock": "medieval rock",
    "Medieval Tavern": "medieval tavern",
    "Melodic Dubstep": "melodic dubstep",
    "Melodic Techno": "melodic techno",
    "Metal": "metal",
    "Metal Rock": "metal rock",
    "Metalcore": "metalcore",
    "Middle East": "middle east",
    "Minimal Techno": "minimal techno",
    "Modern Radio": "modern radio",
    "Motown / Northern Soul": "motown northern soul",
    "Mumble Rap": "mumble rap",
    "Neo Soul": "neo soul",
    "Neue Romantik": "new romantic",
    "Neurofunk Drum & Bass": "neurofunk drum bass",
    "New Wave": "new wave",
    "Nordic / Viking Folk": "nordic viking folk",
    "Nu Jazz": "nu jazz",
    "Nu Metal": "nu metal",
    "Oberkrainer": "oberkrainer alpine folk",
    "Orchestral": "orchestral",
    "Orchestral Hybrid": "orchestral hybrid",
    "Orchestral Score": "orchestral score",
    "Outlaw Country": "outlaw country",
    "Phonk": "phonk",
    "Polka": "polka",
    "Pop": "pop",
    "Pop Punk": "pop punk",
    "Pop Rock": "pop rock",
    "Post Hardcore": "post hardcore",
    "Post Punk": "post punk",
    "Power Metal": "power metal",
    "Progressive House": "progressive house",
    "Progressive Metal": "progressive metal",
    "Progressive Rock": "progressive rock",
    "Psychedelic Rock": "psychedelic rock",
    "Psytrance": "psytrance",
    "Punk": "punk",
    "R&B": "r&b",
    "Raga Rock": "raga rock",
    "Ragtime": "ragtime",
    "Ranchera": "ranchera",
    "Rap": "rap",
    "Reggae": "reggae",
    "Reggaeton": "reggaeton",
    "Retrowave": "retrowave",
    "Rock": "rock",
    "Russian Navy Song": "russian navy song",
    "Salsa": "salsa",
    "Schmutz": "schmutz",
    "Schrammelmusik": "schrammelmusik",
    "Shoegaze": "shoegaze",
    "Ska": "ska",
    "Ska Punk": "ska punk",
    "Skate Rock": "skate rock",
    "Skatecore": "skatecore",
    "Sludge Metal": "sludge metal",
    "Smooth Jazz": "smooth jazz",
    "Soul": "soul",
    "Southern Rock": "southern rock",
    "Space Country": "space country",
    "Space Rock": "space rock",
    "Spaghetti Western": "spaghetti western",
    "Speed Metal": "speed metal",
    "Stoner / Desert Rock": "stoner desert rock",
    "Stubnmusi": "stubnmusi",
    "Sunshine Pop": "sunshine pop",
    "Surf Rock": "surf rock",
    "Symphonic Metal": "symphonic metal",
    "Synthpop": "synthpop",
    "Synthwave": "synthwave",
    "Tango": "tango",
    "Tanzlmusi": "tanzlmusi",
    "Techno": "techno",
    "Techno Pop": "techno pop",
    "Thrash Metal": "thrash metal",
    "Trance": "trance",
    "Trap": "trap",
    "Tribal": "tribal",
    "Tribal House": "tribal house",
    "Tropical House": "tropical house",
    "Tuareg Blues (Desert Blues)": "tuareg blues desert blues",
    "UK Garage / 2 Step": "uk garage 2 step",
    "Video Game / Chiptune": "video game chiptune",
    "Viking Metal": "viking metal",
    "Volkslied": "volkslied",
    "Volksmusik": "volksmusik",
    "Wackelig": "wackelig",
    "West Coast Rap": "west coast rap",
    "Western": "western",
    "Witch House": "witch house",
  },
  "1.3": {
    "AFROBEAT": "afrobeat",
    "AMBIENT / DOWNTEMPO": "ambient downtempo",
    "BLUES": "blues",
    "CINEMATIC SCORE": "cinematic score",
    "CLASSICAL / ORCHESTRAL": "classical orchestral",
    "COUNTRY": "country",
    "ELECTRONIC / DANCE": "electronic dance",
    "EXPERIMENTAL / AVANT GARDE": "experimental avant garde",
    "FOLK & ACOUSTIC": "folk acoustic",
    "FUNK": "funk",
    "HIPHOP & RAP": "hiphop rap",
    "INDUSTRIAL": "industrial",
    "JAZZ": "jazz",
    "LATIN": "latin",
    "METAL": "metal",
    "POP": "pop",
    "PUNK": "punk",
    "R&B": "r&b",
    "REGGAE": "reggae",
    "ROCK": "rock",
    "SCHLAGER": "schlager",
    "SOUL": "soul",
    "SYNTHWAVE / RETROWAVE": "synthwave retrowave",
    "VOLKSMUSIK": "volksmusik",
    "WORLD ETHNIC": "world ethnic",
  },
  "1.4": {
    "80s Retro": "80s retro",
    "90s Vibe": "90s vibe",
    "Acoustic Unplugged": "acoustic unplugged",
    "Chiptune Game": "chiptune game",
    "Cinematic Trailer": "cinematic trailer",
    "City Pop": "city pop",
    "Darkwave": "darkwave",
    "Dreamy Gaze Rock": "dreamy gaze rock",
    "Glitchy Experimental": "glitchy experimental",
    "Modern Radio": "modern radio",
    "Orchestral Hybrid": "orchestral hybrid",
    "Underground Club": "underground club",
    "Vaporwave": "vaporwave",
    "Vintage Analog": "vintage analog",
  },
  "2.1": {
    "Kammerton A4 432 Hz": "432 hz tuning a4",
    "Kammerton A4 440 Hz": "440 hz tuning a4",
  },
  "2.2": {
    "ätherisch & kosmisch": "ethereal cosmic",
    "bedrohlich & spannungsvoll": "ominous tense suspense",
    "bittersüß & hoffnungsvoll": "bittersweet hopeful",
    "dunkel & verspielt": "dark playful",
    "elegant & nächtlich": "elegant nocturnal",
    "futuristisch & technoid": "futuristic techno",
    "gemütlich & festlich": "cozy festive",
    "hell & neugierig": "bright curious",
    "heroisch & triumphal": "heroic triumphant",
    "intensiv & kathartisch": "intense cathartic",
    "luxuriös & nostalgisch": "luxurious nostalgic",
    "melancholisch & reflektiert": "melancholic reflective",
    "mystisch & geheimnisvoll": "mystical mysterious",
    "noir & urban": "noir urban",
    "ominös & dystopisch": "ominous dystopian",
    "organisch & erdig": "organic earthy",
    "psychedelisch & surreal": "psychedelic surreal",
    "romantisch & warm": "romantic warm",
    "ruhig & meditativ": "calm meditative",
    "spirituell & andächtig": "spiritual reverent",
    "verspielt & schelmisch": "playful mischievous",
  },
  "2.3": {
    "afrobeats groove": "afrobeats groove",
    "amapiano log-drum sway": "amapiano log drum sway",
    "broken-beat drive": "broken beat drive",
    "cinematic march": "cinematic march",
    "cumbia shuffle": "cumbia shuffle",
    "d&b sprint": "d&b sprint",
    "dancefloor": "dancefloor",
    "disco strut": "disco strut",
    "driving": "driving",
    "four-on-the-floor": "four on the floor",
    "glitch-step jolt": "glitch step jolt",
    "halftime swagger": "halftime swagger",
    "head nod": "head nod",
    "high energy": "high energy",
    "house glide": "house glide",
    "hypnotischer trance-flow": "hypnotic trance flow",
    "intimate close": "intimate close",
    "laid-back swing": "laid back swing",
    "low energy": "low energy",
    "mid energy": "mid energy",
    "mid-tempo bounce": "mid tempo bounce",
    "mosh-pit energie": "mosh pit energy",
    "polyrhythmisch verwoben": "polyrhythmic interwoven",
    "reggae skank": "reggae skank",
    "slow burn": "slow burn",
    "steady pulse": "steady pulse",
    "syncopated funk-push": "syncopated funk push",
    "trap lean": "trap lean",
    "uk-garage skip": "uk garage skip",
    "wide epic": "wide epic",
  },
  "2.4": {
    "animiertes Finale": "animated finale",
    "Bollywood-Feier": "bollywood celebration",
    "Cyberpunk-Neon-Chase": "cyberpunk neon chase",
    "Dark-Academia Kammer": "dark academia chamber",
    "Docu-Andacht Ritual": "documentary ritual reverent",
    "Dungeon-Crawl-Atmosphäre": "dungeon crawl atmosphere",
    "emotional climax": "emotional climax",
    "epischer Trailer-Rise": "epic trailer rise",
    "Fairytale Ballet": "fairytale ballet",
    "Familien-Wunder": "family wonder",
    "Horror Tension Pulse": "horror tension pulse",
    "Mittelalter-Taverne": "medieval tavern",
    "Mystischer Wald-Quest": "mystical forest quest",
    "Natur-Melange Welt": "nature montage world",
    "Noir-City im Regen": "noir city rain",
    "Ocean-Look Panorama": "ocean vista panorama",
    "Retro-Arcade Montage": "retro arcade montage",
    "Rom-Com Glow": "rom com glow",
    "Sci-Fi Erkundung": "sci fi exploration",
    "Short-Victory Montage": "short victory montage",
    "Space-Opera Vista": "space opera vista",
    "Spaghetti-Western-Showdown": "spaghetti western showdown",
    "Steampunk-Parade": "steampunk parade",
    "whimsical & classy": "whimsical classy",
    "Wikinger-Saga": "viking saga",
  },
  "3.1": {
    "5nne=VokarcDn": "5nne=vokarcdn",
    "A cappella Chor (A cappella)": "a cappella choir",
    "Ad libs": "ad libs",
    "Background Vocals": "background vocals",
    "Call & Response": "call and response",
    "Chant": "chant",
    "Chor (Choir)": "choir",
    "Dialogue (Dialog)": "dialogue",
    "Duett (m + w) (Duo)": "duet male female",
    "Gang Shouts": "gang shouts",
    "Hook Chorus Focus": "hook chorus focus",
    "Instrumental Lead E Gitarre": "instrumental lead electric guitar",
    "Instrumental Lead Piano": "instrumental lead piano",
    "Instrumental Lead Saxophon": "instrumental lead saxophone",
    "Instrumental Lead Synth": "instrumental lead synth",
    "Instrumental Lead Violine": "instrumental lead violin",
    "Instrumental ohne Gesang (Instrumental)": "instrumental",
    "Kehlkopf Obertongesang": "throat singing overtone",
    "Kinderchor Lead": "children choir lead",
    "Lead + Chor Pads": "lead plus choir pads",
    "Lead Vocal (m)": "lead vocal male",
    "Lead Vocal (w)": "lead vocal female",
    "Opern Stimme": "opera voice",
    "Pfeifen / Humming Lead": "whistling humming lead",
    "Rap Verses": "rap verses",
    "Rap Vocal": "rap vocal",
    "Rap Vocal Flow": "rap vocal flow",
    "Rhythmic Spoken Vocals": "rhythmic spoken vocals",
    "Scat / Jazz Vocal": "scat jazz vocal",
    "Spoken Vocals": "spoken vocals",
    "Spoken Word / Erzähler (Spoken Word)": "spoken word narrator",
    "Talk sing": "talk sing",
    "Talk singing": "talk singing",
    "Talk singing rhythmic": "talk singing rhythmic",
    "Vocal Song": "vocal song",
    "World Saiten Lead (Sitar / Oud / Baglama)": "world strings lead sitar oud baglama",
  },
  "3.2": {
    "Aggressive": "aggressive",
    "Airy Whisper": "airy whisper",
    "Bariton Crooner (m)": "bariton crooner m",
    "Deep and dirty": "deep and dirty",
    "Dramatic": "dramatic",
    "Dreamy": "dreamy",
    "Emotional": "emotional",
    "Energetic": "energetic",
    "Falsett Lead (m)": "falsett lead m",
    "Female Alto": "female alto",
    "Female Soprano": "female soprano",
    "Flüster Gesang intim": "intimate whisper vocals",
    "Intimate": "intimate",
    "Male Baritone": "male baritone",
    "Male Tenor": "male tenor",
    "Playful": "playful",
    "Power Belt (w)": "power belt w",
    "Powerful Belt": "powerful belt",
    "Scream / Harsh Vocal": "scream harsh vocal",
    "Smooth Croon": "smooth croon",
    "Soulful": "soulful",
  },
  "3.3": {
    "Aggressive": "aggressive",
    "Deep and dirty": "deep and dirty",
    "Dramatic": "dramatic",
    "Dreamy": "dreamy",
    "Emotional": "emotional",
    "Energetic": "energetic",
    "Intimate": "intimate",
    "Playful": "playful",
    "Soulful": "soulful",
    "Talk sing": "talk sing",
  },
  "3.4": {
    "Autotune obvious": "autotune obvious",
    "Autotune subtle": "autotune subtle",
    "Delay throws": "delay throws",
    "Distorted vocal": "distorted vocal",
    "Double tracking": "double tracking",
    "Harmonies": "harmonies",
    "Phone filter": "phone filter",
    "Reverb heavy": "reverb heavy",
    "Vocoder": "vocoder",
    "Vocoder Robot Lead": "vocoder robot lead",
  },
  "3.5": {
    "Acapella": "acapella",
    "Chor": "chor",
  },
  "4.1": {
    "Humanized loose": "humanized loose",
    "Hybrid electronic live": "hybrid electronic live",
    "Live band": "live band",
    "Live drums": "live drums",
    "One take live feel": "one take live feel",
    "Programmed drums": "programmed drums",
    "Quantized tight": "quantized tight",
    "Studio polished": "studio polished",
  },
  "4.2": {
    "3 bis 5 stimmige Layers": "3 bis 5 stimmige layers",
    "Chaotisch / Überladen": "chaotisch überladen",
    "Full": "full",
    "Gestapelte Chor Pads": "gestapelte chor pads",
    "Intimes Duo mit Raum": "intimes duo mit raum",
    "Kontrapunktisches Gewebe": "kontrapunktisches gewebe",
    "Layered": "layered",
    "Lush": "lush",
    "Lush Strings / Pad Beds": "lush strings pad beds",
    "Minimal": "minimal",
    "Mittlere Dichte Groove Pocket": "mittlere dichte groove pocket",
    "Ostinato Motor + Motive": "ostinato motor motive",
    "Pointillistische Plucks": "pointillistische plucks",
    "Rhythmische Mosaik Verzahnung": "rhythmische mosaik verzahnung",
    "Sparse": "sparse",
    "Subtile Pad Unterlage": "subtile pad unterlage",
    "Tightes Trio Pocket": "tightes trio pocket",
    "Ultra minimal Mono Linie + Drone": "ultra minimal mono linie drone",
    "Wall of sound": "wall of sound",
  },
  "4.3": {
    "Breite Stereo Bühne": "breite stereo bühne",
    "Dry intimate": "dry intimate",
    "Intimate close": "intimate close",
    "Negative space stop and go": "negative space stop and go",
    "Roomy": "roomy",
    "Trocken nah kleiner Raum": "trocken nah kleiner raum",
    "Wide cinematic": "wide cinematic",
    "Wide epic": "wide epic",
  },
  "4.4": {
    "Airy": "airy",
    "Clean": "clean",
    "Druckvoll komprimiert": "druckvoll komprimiert",
    "Glitch Schwarm micro edits": "glitch schwarm micro edits",
    "Gritty": "gritty",
    "Noisy lo fi grit": "noisy lo fi grit",
    "Percussive barrage": "percussive barrage",
    "Sättigungs haze": "sättigungs haze",
    "Sidechain atmen": "sidechain atmen",
  },
  "4.5": {
    "Breakdown getriebene dynamik": "breakdown getriebene dynamik",
    "Entwicklung dünn -> dicht": "entwicklung dünn > dicht",
    "Explosive drop": "explosive drop",
    "Kinematische swells / crescendi": "kinematische swells crescendi",
    "Kontrast dünne Verse / große drops": "kontrast dünne verse große drops",
    "Steady pulse": "steady pulse",
    "Traum mit verwachsenem hall": "traum mit verwachsenem hall",
  },
  "5.1": {
    "100 BPM": "100 bpm",
    "108 BPM": "108 bpm",
    "120 BPM": "120 bpm",
    "128 BPM": "128 bpm",
    "138 BPM": "138 bpm",
    "140 BPM": "140 bpm",
    "150 BPM": "150 bpm",
    "160 BPM": "160 bpm",
    "170 BPM": "170 bpm",
    "60 BPM": "60 bpm",
    "70 BPM": "70 bpm",
    "72 BPM": "72 bpm",
    "80 BPM": "80 bpm",
    "84 BPM": "84 bpm",
    "90 BPM": "90 bpm",
    "96 BPM": "96 bpm",
  },
  "5.2": {
    "4 on the floor": "4 on the floor",
    "breakbeat": "breakbeat",
    "doubletime": "doubletime",
    "funk pocket": "funk pocket",
    "halftime": "halftime",
    "jamaica groove skank": "jamaica groove skank",
    "latin groove": "latin groove",
    "offbeat": "offbeat",
    "shuffle": "shuffle",
    "straight": "straight",
    "swing": "swing",
    "syncopated": "syncopated",
  },
  "5.3": {
    "12/8": "12 8",
    "3/4": "3 4",
    "4/4": "4 4",
    "5/4": "5 4",
    "6/8": "6 8",
    "7/8": "7 8",
    "metric modulation": "metric modulation",
    "polyrhythmic": "polyrhythmic",
  },
  "6.1": {
    "big arena kit": "big arena kit",
    "dnb crisp kit": "dnb crisp kit",
    "dry vintage kit": "dry vintage kit",
    "funk tight snare": "funk tight snare",
    "jazz brush kit": "jazz brush kit",
    "lo fi dusty kit": "lo fi dusty kit",
    "techno kick focused": "techno kick focused",
    "tight punchy kit": "tight punchy kit",
    "trap 808 kit": "trap 808 kit",
  },
  "6.2": {
    "complex fills": "complex fills",
    "ghost notes": "ghost notes",
    "glitch cuts": "glitch cuts",
    "humanized": "humanized",
    "machine tight": "machine tight",
    "minimal groove": "minimal groove",
    "rolling patterns": "rolling patterns",
    "stop start breaks": "stop start breaks",
    "stutter edits": "stutter edits",
  },
  "6.3": {
    "broken hats": "broken hats",
    "crisp hi hats": "crisp hi hats",
    "hat triplets": "hat triplets",
    "muted hats": "muted hats",
    "open hat accents": "open hat accents",
    "ride driven": "ride driven",
    "shaker hats": "shaker hats",
    "splashy cymbals": "splashy cymbals",
  },
  "7.1": {
    "agogo": "agogo",
    "bar chimes": "bar chimes",
    "body drum": "body drum",
    "bongos": "bongos",
    "cajon": "cajon",
    "claves": "claves",
    "congas": "congas",
    "darbuka": "darbuka",
    "djembe": "djembe",
    "tabla": "tabla",
    "taiko": "taiko",
    "timbales": "timbales",
    "wather drum": "wather drum",
  },
  "7.2": {
    "cowbell": "cowbell",
    "finger percussion": "finger percussion",
    "hand claps": "hand claps",
    "maracas": "maracas",
    "rain stick": "rain stick",
    "rim clicks": "rim clicks",
    "snaps": "snaps",
    "stomp claps": "stomp claps",
    "tambourine": "tambourine",
    "triangle": "triangle",
    "woodblocks": "woodblocks",
  },
  "7.3": {
    "gated hits": "gated hits",
    "granular ticks": "granular ticks",
    "impacts": "impacts",
    "reverse hits": "reverse hits",
    "risers": "risers",
    "tape stop": "tape stop",
    "vinyl crackle": "vinyl crackle",
    "whooshes": "whooshes",
  },
  "8.1": {
    "808 bass": "808 bass",
    "acid bass": "acid bass",
    "electric bass": "electric bass",
    "funk slap bass": "funk slap bass",
    "reese bass": "reese bass",
    "sub bass": "sub bass",
    "synth bass": "synth bass",
    "upright bass": "upright bass",
  },
  "8.2": {
    "melodic bassline": "melodic bassline",
    "octave jumps": "octave jumps",
    "simple root notes": "simple root notes",
    "sliding glides": "sliding glides",
    "staccato pulses": "staccato pulses",
    "sustained notes": "sustained notes",
    "syncopated funk": "syncopated funk",
    "walking bass": "walking bass",
  },
  "8.3": {
    "clean DI": "clean di",
    "deep sub heavy": "deep sub heavy",
    "distorted": "distorted",
    "gritty amp": "gritty amp",
    "lo fi muffled": "lo fi muffled",
    "mid bass growl": "mid bass growl",
    "sidechained pump": "sidechained pump",
    "warm round": "warm round",
  },
  "9.1": {
    "acoustic strumming": "acoustic strumming",
    "arpeggios": "arpeggios",
    "clean chords": "clean chords",
    "funk comping": "funk comping",
    "lead guitar": "lead guitar",
    "palm mute chugs": "palm mute chugs",
    "rhythm guitar": "rhythm guitar",
    "riffs": "riffs",
  },
  "9.2": {
    "call and response": "call and response",
    "catchy riff hook": "catchy riff hook",
    "harmonized leads": "harmonized leads",
    "melodic lead hook": "melodic lead hook",
    "octave lead": "octave lead",
    "tremolo picking": "tremolo picking",
    "wah lead": "wah lead",
  },
  "9.3": {
    "clean chorus": "clean chorus",
    "crunchy overdrive": "crunchy overdrive",
    "delay shimmer": "delay shimmer",
    "fuzz": "fuzz",
    "heavy distortion": "heavy distortion",
    "phaser": "phaser",
    "spring reverb": "spring reverb",
    "tape echo": "tape echo",
    "wah wah": "wah wah",
  },
  "10.1": {
    "bell keys": "bell keys",
    "brass stabs": "brass stabs",
    "clavinet": "clavinet",
    "electric piano": "electric piano",
    "harpsichord": "harpsichord",
    "organ": "organ",
    "piano": "piano",
    "strings pad": "strings pad",
  },
  "10.2": {
    "analog mono lead": "analog mono lead",
    "arpeggiator": "arpeggiator",
    "fm keys": "fm keys",
    "pluck synth": "pluck synth",
    "step seq pattern": "step seq pattern",
    "supersaw lead": "supersaw lead",
    "trance gate": "trance gate",
    "wavetable motion": "wavetable motion",
  },
  "10.3": {
    "celesta": "celesta",
    "daumen klavier": "daumen klavier",
    "glockenspiel": "glockenspiel",
    "kalimba": "kalimba",
    "marimba": "marimba",
    "maul trommel": "maul trommel",
    "music box": "music box",
    "shrutibox": "shrutibox",
    "theremin": "theremin",
    "toy piano": "toy piano",
    "vibraphone": "vibraphone",
  },
  "11.1": {
    "accent risers": "accent risers",
    "ear candy": "ear candy",
    "glitch sprinkles": "glitch sprinkles",
    "laser synth hits": "laser synth hits",
    "one shot samples": "one shot samples",
    "surprise stops": "surprise stops",
    "tiny fills": "tiny fills",
    "vocal chops": "vocal chops",
  },
  "11.2": {
    "big reverb": "big reverb",
    "dub delay": "dub delay",
    "gated reverb": "gated reverb",
    "long tail ambience": "long tail ambience",
    "ping pong delay": "ping pong delay",
    "shimmer reverb": "shimmer reverb",
    "slapback delay": "slapback delay",
    "small room": "small room",
  },
  "11.3": {
    "dropout breaks": "dropout breaks",
    "filter break": "filter break",
    "half bar pause": "half bar pause",
    "pre drop silence": "pre drop silence",
    "sparse breakdown": "sparse breakdown",
    "stop time hits": "stop time hits",
    "sudden mute": "sudden mute",
  },
  "12.1": {
    "dorian": "dorian",
    "harmonic minor": "harmonic minor",
    "lydian": "lydian",
    "major key bright": "major key bright",
    "minor key dark": "minor key dark",
    "modal": "modal",
    "pentatonic": "pentatonic",
    "phrygian": "phrygian",
  },
  "12.2": {
    "jazzy extended chords": "jazzy extended chords",
    "lush voicings": "lush voicings",
    "open wide voicings": "open wide voicings",
    "power chords": "power chords",
    "simple triads": "simple triads",
    "sus chords": "sus chords",
    "tight close voicings": "tight close voicings",
  },
  "12.3": {
    "chromatic passing chords": "chromatic passing chords",
    "dissonant spice": "dissonant spice",
    "key change": "key change",
    "modulation": "modulation",
    "pedal point": "pedal point",
    "polytonal touch": "polytonal touch",
    "resolving cadence": "resolving cadence",
    "tension release": "tension release",
  },
  "13.1": {
    "build drop build drop": "build drop build drop",
    "cinematic arc": "cinematic arc",
    "intro verse chorus verse chorus bridge final chorus outro": "intro verse chorus verse chorus bridge final chorus outro",
    "loop based": "loop based",
    "through composed": "through composed",
    "verse prechorus chorus": "verse prechorus chorus",
  },
  "13.2": {
    "bass solo": "bass solo",
    "drum break": "drum break",
    "guitar solo": "guitar solo",
    "no solo": "no solo",
    "piano solo": "piano solo",
    "sax solo": "sax solo",
    "synth solo": "synth solo",
  },
  "13.3": {
    "abrupt stop": "abrupt stop",
    "big ending hit": "big ending hit",
    "fade out": "fade out",
    "long ambient tail": "long ambient tail",
    "quiet acoustic coda": "quiet acoustic coda",
    "reprise ending": "reprise ending",
  },
  "14.1": {
    "big hall": "big hall",
    "cinematic wide": "cinematic wide",
    "dry close": "dry close",
    "plate reverb": "plate reverb",
    "room ambience": "room ambience",
    "spring reverb": "spring reverb",
  },
  "14.2": {
    "deep front to back": "deep front to back",
    "layered depth": "layered depth",
    "mono centered": "mono centered",
    "tight mono low end": "tight mono low end",
    "wide pads": "wide pads",
    "wide stereo": "wide stereo",
  },
  "14.3": {
    "bright modern": "bright modern",
    "crisp clean": "crisp clean",
    "dark heavy": "dark heavy",
    "keep -3 db headroom": "keep 3 db headroom",
    "lo fi tape": "lo fi tape",
    "natural dynamics": "natural dynamics",
    "output peak -3db": "output peak 3db",
    "premaster mix": "premaster mix",
    "punchy loud": "punchy loud",
    "unmastered mix": "unmastered mix",
    "warm analog": "warm analog",
  },
  "15.1": {
    "acoustic campfire": "acoustic campfire",
    "banjo folk": "banjo folk",
    "comedy novelty": "comedy novelty",
    "dubstep wobble": "dubstep wobble",
    "heavy metal shredding": "heavy metal shredding",
    "jazz swing": "jazz swing",
    "kids music": "kids music",
    "polka": "polka",
    "schlager": "schlager",
  },
  "15.2": {
    "clipping": "clipping",
    "distorted master": "distorted master",
    "excessive reverb": "excessive reverb",
    "harsh sibilance": "harsh sibilance",
    "low quality artifacts": "low quality artifacts",
    "messy drums": "messy drums",
    "muddy mix": "muddy mix",
    "out of tune vocals": "out of tune vocals",
  },
  "15.3": {
    "cheesy inspirational": "cheesy inspirational",
    "comedic tone": "comedic tone",
    "overly happy": "overly happy",
    "overly sad ballad": "overly sad ballad",
    "romantic kitsch": "romantic kitsch",
    "spooky horror": "spooky horror",
  },
  "16.1": {
    "apres ski": "apres ski",
    "ballermann": "ballermann",
    "karaoke backing track": "karaoke backing track",
    "mallorca party": "mallorca party",
    "novelty song": "novelty song",
    "schlager": "schlager",
    "volkstümlich": "volkstümlich",
  },
  "16.2": {
    "cheap midi": "cheap midi",
    "child vocals": "child vocals",
    "chipmunk voice": "chipmunk voice",
    "novelty character voice": "novelty character voice",
    "overly theatrical operatic": "overly theatrical operatic",
    "stock presets": "stock presets",
  },
  "17.1": {
    "clean master": "clean master",
    "deep low end": "deep low end",
    "high fidelity": "high fidelity",
    "pristine mix": "pristine mix",
    "punchy transients": "punchy transients",
    "silky highs": "silky highs",
    "studio quality": "studio quality",
  },
  "17.2": {
    "articulate phrasing": "articulate phrasing",
    "clean consonants": "clean consonants",
    "clear german pronunciation": "clear german pronunciation",
    "intelligible vocals": "intelligible vocals",
    "less mumbling": "less mumbling",
    "native german accent": "native german accent",
  },
  "17.3": {
    "Breakbeat": "breakbeat",
    "Federnd": "bouncy springy",
    "Pulsierend": "pulsating",
    "Schwingen": "swinging groove",
    "Skittern": "skittering",
    "Sputtern": "stuttering glitchy",
    "Staccato": "staccato",
    "Tanzbar": "danceable club",
  },
  "17.4": {
    "Binaural": "binaural",
    "Bitcrushed": "bitcrushed",
    "Feldaufnahmen": "field recordings ambience",
    "Nachhall": "reverb ambience",
    "Panne": "glitch error",
    "Übersteuert": "overdriven distorted",
  },
  "17.5": {
    "Eindringlich": "haunting intense",
    "Euphorisch": "euphoric",
    "Gedämpft": "muted subdued",
    "Geheimnisvoll": "mysterious",
    "Gruselig": "creepy spooky",
    "Hell": "bright",
    "Himmlisch": "heavenly",
    "Hohe Energie": "high energy",
    "Hypnotisch": "hypnotic",
    "Melancholisch": "melancholic",
    "Nervös": "nervous tense",
    "Schwer": "heavy",
    "Spannend": "tense suspense",
    "Surreal": "surreal",
    "Süß": "sweet",
    "Transzendent": "transcendent",
    "Tropisch": "tropisch",
    "Wohlfühlen": "cozy feel good",
  },
  "17.6": {
    "Basslastig": "bass heavy",
    "Bissig": "biting",
    "Brutzelnd": "crackling",
    "Collage": "collage",
    "Geschichtet": "layered",
    "Klangcollage": "sound collage",
    "Minimalistisch": "minimal",
    "Schlammig": "muddy",
    "Seidig": "silky",
    "Sonic": "sonic",
    "Spacey": "spacey",
    "Spärlich": "sparse",
    "Spektral": "spectral",
    "Stachelig": "spiky",
    "Synthetisch": "synthetic",
    "Textural": "textural",
    "Tiefer Bass": "deep bass",
    "Tonal": "tonal",
    "Üppig": "lush",
  },
  "17.7": {
    "Ausgefallen": "quirky unusual",
    "Dampfig": "hazy steamy",
    "Donnernd": "thundering",
    "Eklektisch": "eclectic",
    "Elektronisch beeinflusst": "electronically influenced",
    "Experimentelle Elektronik": "experimental electronic",
    "Genreübergreifend": "cross genre",
    "Geschleift": "grinding",
    "Gezahnt": "jagged sawtooth",
    "Glatt": "smooth",
    "Indie beeinflusst": "indie influenced",
    "Industrieller Sound": "industrial sound",
    "Kammer": "chamber",
    "Klagend": "wailing lament",
    "Klassisch": "classical",
    "Mikrotonal": "mikrotonal",
    "Mutig": "bold",
    "Neoklassizistisch": "neoclassical",
    "Phasenweise": "phased",
    "Pionierarbeit": "pioneering",
    "Progressiv": "progressiv",
    "Raffiniert": "refined",
    "Rebellisch": "rebellious",
    "Retro": "retro",
    "Rifflastig": "riff heavy",
    "Satirisch": "satirical",
    "Stellar": "stellar",
    "Straße": "street",
    "Sumpfig": "swampy",
    "Thematisch": "thematisch",
    "Verblasst": "faded",
    "Vom Land geprägt": "rural",
  },
  "18.1": {
    "baritone saxophone": "baritone saxophone",
    "bass clarinet": "bass clarinet",
    "bass flute": "bass flute",
    "bass saxophone": "bass saxophone",
    "blues harmonika": "blues harmonika",
    "contrabass clarinet": "contrabass clarinet",
    "contrabass flute": "contrabass flute",
    "contrabass saxophone": "contrabass saxophone",
    "didgeridoo": "didgeridoo",
    "duduk": "duduk",
    "fujara": "fujara",
    "sarrusophone": "sarrusophone",
    "shakuhachi": "shakuhachi",
  },
  "18.2": {
    "alpine zither": "alpine zither",
    "balalaika": "balalaika",
    "berimbau": "berimbau",
    "bouzouki": "bouzouki",
    "hammered dulcimer": "hammered dulcimer",
    "harp": "harp",
    "hurdy gurdy": "hurdy gurdy",
    "kalimba": "kalimba",
    "kora": "kora",
    "koto": "koto",
    "nyckelharpa": "nyckelharpa",
    "oud": "oud",
    "saz": "saz",
    "shamisen": "shamisen",
    "sitar": "sitar",
  },
  "18.3": {
    "bodhran": "bodhran",
    "bougarabou": "bougarabou",
    "darbuka": "darbuka",
    "djembe": "djembe",
    "frame drum": "frame drum",
    "goumbe": "hand drum conga djembe style gombe earthy",
    "tabla": "tabla",
    "taiko": "taiko",
    "talking drum": "talking drum",
    "timbales": "timbales",
    "udu drum": "udu drum",
  },
  "19.1": {
    "high style impact": "high style impact",
    "low style impact": "low style impact",
    "medium style impact": "medium style impact",
  },
  "19.2": {
    "high weirdness": "high weirdness",
    "low weirdness": "low weirdness",
    "medium weirdness": "medium weirdness",
  },
  "20.1": {
    "2000s": "2000s",
    "2010s": "2010s",
    "60s": "60s",
    "70s": "70s",
    "80s": "80s",
    "90s": "90s",
    "modern": "modern",
    "retro": "retro",
  },
  "20.2": {
    "analog tape": "analog tape",
    "cinematic mix": "cinematic mix",
    "club mix": "club mix",
    "dry close mic": "dry close mic",
    "live room": "live room",
    "radio ready": "radio ready",
    "vinyl era": "vinyl era",
    "wide stadium": "wide stadium",
  },
  "21.1": {
    "chorus anthem": "chorus anthem",
    "earworm riff": "earworm riff",
    "hook heavy": "hook heavy",
    "minimal hook": "minimal hook",
    "strong motif": "strong motif",
  },
  "21.2": {
    "big drop": "big drop",
    "slow build": "slow build",
    "steady hypnotic": "steady hypnotic",
    "sudden breaks": "sudden breaks",
    "tension and release": "tension and release",
  },
  "22.1": {
    "[<specific instrument>]": "[<specific instrument>]",
    "[<vocals>]": "[<vocals>]",
    "[Break]": "[Break]",
    "[Bridge]": "[Bridge]",
    "[Build]": "[Build]",
    "[Chorus]": "[Chorus]",
    "[End]": "[End]",
    "[Hook]": "[Hook]",
    "[Instrumental]": "[Instrumental]",
    "[Interlude]": "[Interlude]",
    "[Intro]": "[Intro]",
    "[Movement]": "[Movement]",
    "[Outro]": "[Outro]",
    "[Pre-Chorus]": "[Pre-Chorus]",
    "[Solo]": "[Solo]",
    "[Verse]": "[Verse]",
  },
  "22.2": {
    "[INTRO ambient pads 4 bars]": "[INTRO ambient pads 4 bars]",
    "[INTRO choir swell 4 bars]": "[INTRO choir swell 4 bars]",
    "[INTRO drum pickup 2 bars]": "[INTRO drum pickup 2 bars]",
    "[INTRO guitar riff 4 bars]": "[INTRO guitar riff 4 bars]",
    "[INTRO instrumental 4 bars]": "[INTRO instrumental 4 bars]",
    "[INTRO instrumental 8 bars]": "[INTRO instrumental 8 bars]",
    "[INTRO spoken tag 2 bars]": "[INTRO spoken tag 2 bars]",
  },
  "22.3": {
    "[BREAK 2 bars]": "[BREAK 2 bars]",
    "[BUILD 4 bars]": "[BUILD 4 bars]",
    "[DROP-IN 1 bar]": "[DROP-IN 1 bar]",
    "[PRE-CHORUS 4 bars]": "[PRE-CHORUS 4 bars]",
    "[PRE-VERSE 2 bars]": "[PRE-VERSE 2 bars]",
    "[PRE-VERSE 4 bars]": "[PRE-VERSE 4 bars]",
  },
  "22.4": {
    "[VERSE 12 bars]": "[VERSE 12 bars]",
    "[VERSE 16 bars]": "[VERSE 16 bars]",
    "[VERSE 8 bars]": "[VERSE 8 bars]",
    "[VERSE half-time 8 bars]": "[VERSE half-time 8 bars]",
    "[VERSE minimal 8 bars]": "[VERSE minimal 8 bars]",
    "[VERSE rap 16 bars]": "[VERSE rap 16 bars]",
  },
  "23.1": {
    "[CHORUS 12 bars]": "[CHORUS 12 bars]",
    "[CHORUS 8 bars]": "[CHORUS 8 bars]",
    "[CHORUS anthem 8 bars]": "[CHORUS anthem 8 bars]",
    "[CHORUS choir 8 bars]": "[CHORUS choir 8 bars]",
    "[CHORUS double-time 8 bars]": "[CHORUS double-time 8 bars]",
    "[CHORUS hook-only 8 bars]": "[CHORUS hook-only 8 bars]",
  },
  "23.2": {
    "[BREAKDOWN 8 bars]": "[BREAKDOWN 8 bars]",
    "[BRIDGE 12 bars]": "[BRIDGE 12 bars]",
    "[BRIDGE 8 bars]": "[BRIDGE 8 bars]",
    "[DROP 8 bars]": "[DROP 8 bars]",
    "[INSTRUMENTAL BREAK 8 bars]": "[INSTRUMENTAL BREAK 8 bars]",
    "[SOLO 16 bars]": "[SOLO 16 bars]",
    "[SOLO 8 bars]": "[SOLO 8 bars]",
  },
  "23.3": {
    "[CHORUS twice]": "[CHORUS twice]",
    "[CHORUS with key lift]": "[CHORUS with key lift]",
    "[CHORUS with new drums]": "[CHORUS with new drums]",
    "[FINAL CHORUS extended]": "[FINAL CHORUS extended]",
    "[VERSE then CHORUS repeat]": "[VERSE then CHORUS repeat]",
  },
  "24.1": {
    "[FINAL CHORUS 12 bars]": "[FINAL CHORUS 12 bars]",
    "[FINAL CHORUS 16 bars]": "[FINAL CHORUS 16 bars]",
    "[FINAL CHORUS big ending]": "[FINAL CHORUS big ending]",
    "[FINAL CHORUS half-time]": "[FINAL CHORUS half-time]",
    "[FINAL CHORUS quiet lift]": "[FINAL CHORUS quiet lift]",
  },
  "24.2": {
    "[OUTRO acoustic coda]": "[OUTRO acoustic coda]",
    "[OUTRO ambient tail]": "[OUTRO ambient tail]",
    "[OUTRO fade out]": "[OUTRO fade out]",
    "[OUTRO hard stop]": "[OUTRO hard stop]",
    "[OUTRO instrumental 4 bars]": "[OUTRO instrumental 4 bars]",
    "[OUTRO instrumental 8 bars]": "[OUTRO instrumental 8 bars]",
  },
  "24.3": {
    "[A CAPPELLA END]": "[A CAPPELLA END]",
    "[CHOIR CODA]": "[CHOIR CODA]",
    "[DROP TO MINIMAL]": "[DROP TO MINIMAL]",
    "[DRUMS ONLY BREAK]": "[DRUMS ONLY BREAK]",
    "[KEY CHANGE up]": "[KEY CHANGE up]",
    "[TEMPO SHIFT]": "[TEMPO SHIFT]",
  },
  "25.1": {
    "add bass line": "add bass line",
    "add brass stabs": "add brass stabs",
    "add countermelody": "add countermelody",
    "add drums variation": "add drums variation",
    "add guitar layer": "add guitar layer",
    "add lead melody": "add lead melody",
    "add percussion layer": "add percussion layer",
    "add piano layer": "add piano layer",
    "add strings layer": "add strings layer",
    "add synth pads": "add synth pads",
  },
  "25.2": {
    "from existing suno song": "from existing suno song",
    "from stem timeline": "from stem timeline",
    "from uploaded reference": "from uploaded reference",
    "match the current groove": "match the current groove",
    "match the current harmony": "match the current harmony",
    "match the current tempo": "match the current tempo",
  },
  "25.3": {
    "bold layer": "bold layer",
    "experimental layer": "experimental layer",
    "medium arrangement": "medium arrangement",
    "minimal layer only": "minimal layer only",
    "no extra instruments": "no extra instruments",
    "sparse only": "sparse only",
    "subtle support": "subtle support",
  },
  "26.1": {
    "keep chord progression": "keep chord progression",
    "keep drum pattern": "keep drum pattern",
    "keep groove pocket": "keep groove pocket",
    "keep key center": "keep key center",
    "keep melody untouched": "keep melody untouched",
    "keep tempo locked": "keep tempo locked",
    "keep vocal untouched": "keep vocal untouched",
  },
  "26.2": {
    "background texture": "background texture",
    "foreground lead": "foreground lead",
    "left right call": "left right call",
    "mid support": "mid support",
    "mono center": "mono center",
    "tucked under vocals": "tucked under vocals",
    "wide stereo bed": "wide stereo bed",
  },
  "26.3": {
    "amp grit": "amp grit",
    "cinematic wide": "cinematic wide",
    "clean DI": "clean di",
    "dark moody": "dark moody",
    "lo fi texture": "lo fi texture",
    "modern bright": "modern bright",
    "pristine studio": "pristine studio",
    "warm analog": "warm analog",
  },
  "27.1": {
    "add only in breakdown": "add only in breakdown",
    "add only in bridge": "add only in bridge",
    "add only in choruses": "add only in choruses",
    "add only in intro": "add only in intro",
    "add only in outro": "add only in outro",
    "add only in verses": "add only in verses",
    "add throughout": "add throughout",
  },
  "27.2": {
    "accent hits only": "accent hits only",
    "arpeggiated": "arpeggiated",
    "call and response": "call and response",
    "ostinato": "ostinato",
    "riff based": "riff based",
    "simple whole notes": "simple whole notes",
    "sparse stabs": "sparse stabs",
    "syncopated pattern": "syncopated pattern",
  },
  "27.3": {
    "complex": "arrangement complexity complex",
    "improvised feel": "improvised feel",
    "medium": "arrangement complexity medium",
    "simple": "arrangement complexity simple",
    "tightly composed": "tightly composed",
    "very complex": "arrangement complexity very complex",
    "very simple": "arrangement complexity very simple",
  },
};

export function normalizeSunoToken(displayText) {
  let t = String(displayText ?? '').trim();
  if (!t || t === NONE) return '';
  if (t.startsWith('[') && t.endsWith(']')) return t;
  t = t.replace(/\br\s*&\s*b\b/gi, 'r__AMP__b');
  t = t.replace(/\bd\s*&\s*b\b/gi, 'd__AMP__b');
  t = t.replace(/[\/+,;|]/g, ' ');
  t = t.replace(/&/g, ' ');
  t = t.replace(/[()]/g, ' ');
  t = t.replace(/[–—-]/g, ' ');
  t = t.replace(/\s+/g, ' ').trim();
  t = t.toLowerCase();
  t = t.replace(/r__amp__b/g, 'r&b');
  t = t.replace(/d__amp__b/g, 'd&b');
  return t;
}

export function toSunoToken(menuKey, displayText) {
  const label = String(displayText ?? '').trim();
  if (!label || label === NONE) return '';
  const bucket = SUNO_TERMS_BY_MENU[String(menuKey ?? '')];
  if (bucket && Object.prototype.hasOwnProperty.call(bucket, label)) return bucket[label];
  return normalizeSunoToken(label);
}
